spring:
  application:
    name: travel-shop


  datasource:
    url: jdbc:mysql://gdfs-travel-shop-backend.czy46y0aw9bh.ap-southeast-2.rds.amazonaws.com:3306/travelshop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: jinkaw-xuZbu9-nitnuc

  jpa:
    hibernate:
      ddl-auto: update